version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: "ci"
    labels:
      - dependencies

  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    commit-message:
      prefix: "chore"
    labels:
      - dependencies
    groups:
      minor-and-patch:
        update-types:
          - minor
          - patch
