blank_issues_enabled: true
contact_links:
  - name: Question or discussion
    url: https://github.com/HilthonTT/OpenChess/discussions
    about: Ask questions and discuss ideas that aren't bugs or feature requests.
